### ISSUE TITLE
Rundungsfehler

### ISSUE THREAD

**Issue by Shoprunners** [PAYONE-GmbH/prestashop-17#1]
Hi,
from time to time we experience payment error because of rounding problems:

![image](https://user-images.githubusercontent.com/4729231/64428512-2e3dbf00-d0b4-11e9-803f-b5b515cbe371.png)

![image](https://user-images.githubusercontent.com/4729231/64428565-53323200-d0b4-11e9-8c4b-318f5188ff55.png)

PS. 1.6 module versin 2.0.1
Is there anything we can do about this? what are the recommended rounding settings for the shop?

**Comment by fjbender** [comment]
We have not experienced any rounding errors in our tests, so it's difficult to give a recommendation, sorry.

Please contact our technical support team so they can help gathering some more info on this issue.
