### ISSUE TITLE
Generate empty PDF

### ISSUE THREAD

**Issue by FlorentJonville** [PAYONE-GmbH/prestashop-17#10]
Hello,

I have a problem with the payment module. When paying, for example by Visa, instead of having a confirmation the module generate an empty PDF with the order reference name ???

I use test card 4111111111111111, with PS 1.7.7.8 and v2.0.8 of module.

Thanks for your help

**Comment by FlorentJonville** [comment]
Hi, 

In addition to my message, here is the return I have on the order form:
FC_PAYONE_ERROR_ORDER_NO_DATA_FOUND

Is this module really in Beta version ? Does anyone pass by here sometime ?

Thanks

**Comment by hreinberger** [comment]
Hi @FlorentJonville 

sorry for keeping you waiting. Could you write to our technical support at tech.support@payone.com and give them your merchant ID? Our colleagues can check your account config and guide you through the next steps. thanks!
