### ISSUE TITLE
SUPP-29383: birthday parameter contains invalid data

### ISSUE THREAD

**Issue by fjbender** [PAYONE-GmbH/prestashop-17#3]
When there is no birthday set within Prestashop, this is mapped to 00000000 for the birthday parameter, which is an invalid value and results in rejection of the API call.

If a date of birth is not available, the parameter shouldn't be sent at all.

**Comment by paeddl** [comment]
Fixed: https://github.com/PAYONE-GmbH/prestashop-17/commit/2700f1356bc13d14f287e8fba6a40a757464f37c

**Comment by fjbender** [comment]
Thanks
