### ISSUE TITLE
Can't install on PS 1.7.7.8

### ISSUE THREAD

**Issue by mdb44** [PAYONE-GmbH/prestashop-17#8]
Hi there. I tried to install the last version on 1.7.7.8 but everytime i have the error message saying "This file does not seem to be a valid module zip".
Is there any known compatibilty issue?
Thanks !

**Comment by paeddl** [comment]
@mdb44 there's no know issue, works on all our 1.7.7.8 test-instances. Where did you load the ZIP from? Did you just create it out of github? Then you need to follow the exact steps you can find here: https://docs.payone.com/display/public/INT/Integrationsanleitung+Presta (2).

**Comment by mdb44** [comment]
Thanks for your fast answer @paeddl 
I tried installing the file straight from Github (prestashop-17-2.0.8.zip) and also tried creating another zip since it failed to install, both from the module manager. None worked. :/
Debug mode didn't reveal anything...

**Comment by paeddl** [comment]
@mdb44 you did the following steps?
- download ZIP from github
- unzip
- rename unziped folder to fcpayone
- zip again (including the renamed folder)
doing these steps, installation works

**Comment by mdb44** [comment]
I'm an idiot. I made a typo in the folder name... Sorry for wasting your time !

**Comment by paeddl** [comment]
@mdb44 no prob
